In [1]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10) # random normal distribution
A

array([ -6.78576020e-01,   9.08738441e-02,  -1.42830873e-03,
         1.58128394e+00,   1.75732632e+00,  -5.80764455e-01,
        -5.04336306e-01,  -1.01223640e+00,   6.89569782e-01,
        -2.94230368e+00])

In [8]:
B = np.random.randn(10)
B

array([ 0.08509197, -1.14374982,  0.2867373 ,  0.32242161,  0.03818807,
       -0.68200698, -1.46420306, -0.61028252,  1.57479506, -0.24529458])

In [9]:
# Binary Functions
np.add(A,B)

array([-0.59348405, -1.05287598,  0.285309  ,  1.90370555,  1.79551439,
       -1.26277144, -1.96853936, -1.62251892,  2.26436484, -3.18759826])

In [11]:
np.maximum(A,B)  # maximum between two arrays - indexwise comparison

array([ 0.08509197,  0.09087384,  0.2867373 ,  1.58128394,  1.75732632,
       -0.58076445, -0.50433631, -0.61028252,  1.57479506, -0.24529458])

In [12]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True