In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape((3,3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
type(arr1)

numpy.ndarray

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [12]:
type(ser1)

pandas.core.series.Series

### np.concatenate works only for axis=0 (for panda Series)

In [10]:
np.concatenate([ser1,ser2],axis=0)

array([0, 1, 2, 3, 4])

In [8]:
ser1

T    0
U    1
V    2
dtype: int64

In [9]:
ser2

X    3
Y    4
dtype: int64

### use pd.concat for series with index

In [10]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2],axis=1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [12]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [13]:
dframe1 = DataFrame(np.random.rand(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.rand(3,3),columns=['Y','Q','X'])

In [14]:
dframe1

X         Y         Z
0  0.300522  0.148752  0.535201
1  0.423313  0.422103  0.034191
2  0.295434  0.444925  0.632997
3  0.549285  0.157810  0.505141

In [15]:
dframe2

Y         Q         X
0  0.191211  0.231461  0.509358
1  0.141849  0.508300  0.235271
2  0.231619  0.944137  0.168632

In [16]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.300522  0.148752  0.535201
1       NaN  0.423313  0.422103  0.034191
2       NaN  0.295434  0.444925  0.632997
3       NaN  0.549285  0.157810  0.505141
0  0.231461  0.509358  0.191211       NaN
1  0.508300  0.235271  0.141849       NaN
2  0.944137  0.168632  0.231619       NaN

## makes index in order starting 0

In [17]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN  0.300522  0.148752  0.535201
1       NaN  0.423313  0.422103  0.034191
2       NaN  0.295434  0.444925  0.632997
3       NaN  0.549285  0.157810  0.505141
4  0.231461  0.509358  0.191211       NaN
5  0.508300  0.235271  0.141849       NaN
6  0.944137  0.168632  0.231619       NaN